// Code generated by ogen, DO NOT EDIT.
package api

type HandleCancelOrderRes interface {
	handleCancelOrderRes()
}

type HandleCreateOrderRes interface {
	handleCreateOrderRes()
}

type HandleGetOrderRes interface {
	handleGetOrderRes()
}

type HandlePayOrderRes interface {
	handlePayOrderRes()
}
