// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// HandleCancelOrder implements HandleCancelOrder operation.
//
// Отменить заказ.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) HandleCancelOrder(ctx context.Context, params HandleCancelOrderParams) (r HandleCancelOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// HandleCreateOrder implements HandleCreateOrder operation.
//
// Создает новый заказ на основе деталей.
//
// POST /api/v1/orders
func (UnimplementedHandler) HandleCreateOrder(ctx context.Context, req *CreateOrderRequest) (r HandleCreateOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// HandleGetOrder implements HandleGetOrder operation.
//
// Получить заказ по UUID.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) HandleGetOrder(ctx context.Context, params HandleGetOrderParams) (r HandleGetOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// HandlePayOrder implements HandlePayOrder operation.
//
// Проводит оплату заказа.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) HandlePayOrder(ctx context.Context, req *PayOrderRequest, params HandlePayOrderParams) (r HandlePayOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}
