// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "order/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// InventoryClient is an autogenerated mock type for the InventoryClient type
type InventoryClient struct {
	mock.Mock
}

type InventoryClient_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryClient) EXPECT() *InventoryClient_Expecter {
	return &InventoryClient_Expecter{mock: &_m.Mock}
}

// ListParts provides a mock function with given fields: ctx, partsUUID
func (_m *InventoryClient) ListParts(ctx context.Context, partsUUID []string) ([]*entity.Part, error) {
	ret := _m.Called(ctx, partsUUID)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []*entity.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*entity.Part, error)); ok {
		return rf(ctx, partsUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*entity.Part); ok {
		r0 = rf(ctx, partsUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, partsUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryClient_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type InventoryClient_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - partsUUID []string
func (_e *InventoryClient_Expecter) ListParts(ctx interface{}, partsUUID interface{}) *InventoryClient_ListParts_Call {
	return &InventoryClient_ListParts_Call{Call: _e.mock.On("ListParts", ctx, partsUUID)}
}

func (_c *InventoryClient_ListParts_Call) Run(run func(ctx context.Context, partsUUID []string)) *InventoryClient_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *InventoryClient_ListParts_Call) Return(_a0 []*entity.Part, _a1 error) *InventoryClient_ListParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryClient_ListParts_Call) RunAndReturn(run func(context.Context, []string) ([]*entity.Part, error)) *InventoryClient_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryClient creates a new instance of InventoryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryClient {
	mock := &InventoryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
