// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: kafka/events/order_paid/order_paid.proto

package order_paid

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderPaid struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventUUID       string                 `protobuf:"bytes,1,opt,name=EventUUID,proto3" json:"EventUUID,omitempty"`
	OrderUUID       string                 `protobuf:"bytes,2,opt,name=OrderUUID,proto3" json:"OrderUUID,omitempty"`
	UserUUID        string                 `protobuf:"bytes,3,opt,name=UserUUID,proto3" json:"UserUUID,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,4,opt,name=PaymentMethod,proto3" json:"PaymentMethod,omitempty"`
	TransactionUUID string                 `protobuf:"bytes,5,opt,name=TransactionUUID,proto3" json:"TransactionUUID,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderPaid) Reset() {
	*x = OrderPaid{}
	mi := &file_kafka_events_order_paid_order_paid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPaid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPaid) ProtoMessage() {}

func (x *OrderPaid) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_events_order_paid_order_paid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPaid.ProtoReflect.Descriptor instead.
func (*OrderPaid) Descriptor() ([]byte, []int) {
	return file_kafka_events_order_paid_order_paid_proto_rawDescGZIP(), []int{0}
}

func (x *OrderPaid) GetEventUUID() string {
	if x != nil {
		return x.EventUUID
	}
	return ""
}

func (x *OrderPaid) GetOrderUUID() string {
	if x != nil {
		return x.OrderUUID
	}
	return ""
}

func (x *OrderPaid) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

func (x *OrderPaid) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *OrderPaid) GetTransactionUUID() string {
	if x != nil {
		return x.TransactionUUID
	}
	return ""
}

var File_kafka_events_order_paid_order_paid_proto protoreflect.FileDescriptor

const file_kafka_events_order_paid_order_paid_proto_rawDesc = "" +
	"\n" +
	"(kafka/events/order_paid/order_paid.proto\"\xb3\x01\n" +
	"\tOrderPaid\x12\x1c\n" +
	"\tEventUUID\x18\x01 \x01(\tR\tEventUUID\x12\x1c\n" +
	"\tOrderUUID\x18\x02 \x01(\tR\tOrderUUID\x12\x1a\n" +
	"\bUserUUID\x18\x03 \x01(\tR\bUserUUID\x12$\n" +
	"\rPaymentMethod\x18\x04 \x01(\tR\rPaymentMethod\x12(\n" +
	"\x0fTransactionUUID\x18\x05 \x01(\tR\x0fTransactionUUIDB\x18Z\x16pkg/events/order_paid;b\x06proto3"

var (
	file_kafka_events_order_paid_order_paid_proto_rawDescOnce sync.Once
	file_kafka_events_order_paid_order_paid_proto_rawDescData []byte
)

func file_kafka_events_order_paid_order_paid_proto_rawDescGZIP() []byte {
	file_kafka_events_order_paid_order_paid_proto_rawDescOnce.Do(func() {
		file_kafka_events_order_paid_order_paid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kafka_events_order_paid_order_paid_proto_rawDesc), len(file_kafka_events_order_paid_order_paid_proto_rawDesc)))
	})
	return file_kafka_events_order_paid_order_paid_proto_rawDescData
}

var file_kafka_events_order_paid_order_paid_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kafka_events_order_paid_order_paid_proto_goTypes = []any{
	(*OrderPaid)(nil), // 0: OrderPaid
}
var file_kafka_events_order_paid_order_paid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kafka_events_order_paid_order_paid_proto_init() }
func file_kafka_events_order_paid_order_paid_proto_init() {
	if File_kafka_events_order_paid_order_paid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kafka_events_order_paid_order_paid_proto_rawDesc), len(file_kafka_events_order_paid_order_paid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kafka_events_order_paid_order_paid_proto_goTypes,
		DependencyIndexes: file_kafka_events_order_paid_order_paid_proto_depIdxs,
		MessageInfos:      file_kafka_events_order_paid_order_paid_proto_msgTypes,
	}.Build()
	File_kafka_events_order_paid_order_paid_proto = out.File
	file_kafka_events_order_paid_order_paid_proto_goTypes = nil
	file_kafka_events_order_paid_order_paid_proto_depIdxs = nil
}
