// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	HandleCancelOrderOperation OperationName = "HandleCancelOrder"
	HandleCreateOrderOperation OperationName = "HandleCreateOrder"
	HandleGetOrderOperation    OperationName = "HandleGetOrder"
	HandlePayOrderOperation    OperationName = "HandlePayOrder"
)
